### PR TITLE
Only display "Toggle Inherited fields" when there's a super class, closes #120

### LINKED ISSUE #120: "Toggle Inherited Fields" is generated when there aren't any
For example for [`Array`](http://api.haxe.org/Array.html), it doesn't do much.

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Simn** [comment]
Ideally we would also check if there are any additional fields, but this is a start.

@markknol: Can you make sure that this change gets into the other themes too?

**Comment by markknol** [comment]
I'm not sure if the haxe theme has inherited fields?

**Comment by markknol** [comment]
@Simn In the new haxe theme there is no such thing as inherited fields. http://api.haxe.org/v/dev/js/html/Element.html 
Should we add it?

**Comment by Simn** [comment]
Yeah

**Pull request merged**
