### PR TITLE
Document -D version and -D source-path, closes #138

### LINKED ISSUE #138: -D version and -D source-path are not documented
Not sure if there are other defines that dox and/or the default template use.

What's the best place to document them? Command-line? Readme?

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by Simn** [comment]
Hmm... I'm not trying to be pedantic here, but `-D version` is not exactly special to Dox itself. It just happens to be part of the default theme, which is *kind of* the same thing. `-D source-path` on the other hand is part of `Api.getSourceLink`, so that's fair enough.

Do you think it's worthwhile being more accurate here?

**Comment by Gama11** [comment]
It probably makes sense to mention that it's part of the default theme, but it definitely should be mentioned that `-D version` is a thing.

**Comment by Gama11** [comment]
Updated.

**Comment by Simn** [comment]
Thanks!

**Pull request merged**
