### PR TITLE
Break long parameters on functions, avoid horizontal scroll

### PR DESCRIPTION
**Pull request by markknol**
as seen here http://api.haxe.org/v/dev/haxe/Http.html

### CODE REVIEW

**Comment by markknol** [comment]
breaking

**Comment by Simn** [comment]
I'm not entirely happy with how that wraps yet.

**Comment by markknol** [comment]
Ok ill try if i can make it display inline somehow

**Comment by markknol** [comment]
With latest updates it looks like this.

updated titles

---
I think putting the labels inside the border makes sense, the breaking doesnt look that odd now, in my opinion. I also updated the title style (white background, updated identifier style, found that in the online version, kinda liked that)
---

word-breaking

---

.. also breaks parameter types like this (with non-breaking hypens)

---

nonbreaking-hypens

**Comment by Simn** [comment]
I guess that's fine, but I can't merge the PR. Can you reopen it?

**Pull request closed without merging**
