### PR TITLE
Removes whitespace in front of comment lines (#83)

### PR DESCRIPTION
**Pull request by maxless**
Should fix the original problem in #83 (there's some other stuff in the discussion, though)

### CODE REVIEW

**Comment by Simn** [comment]
This is not so easy because people might put code inside backticks which would lose its indenting. What might work is to determine the minimum indent across all lines, then remove only that many spaces from each line.

Don't ask me how this should interact with tabs though.

**Comment by maxless** [comment]
I don't think backticks with multiple lines inside work correctly. Running the test with:
```
 * `
 * // Iterate over entity's children
 * var child = entity.firstChild;
 * while (child != null) {
 *     var next = child.next; // Store in case the child is removed in process()
 *     process(child);
 *     child = next;
 * }
 * `
```

or
```
		`
 // Iterate over entity's children
 var child = entity.firstChild;
 while (child != null) {
     var next = child.next; // Store in case the child is removed in process()
     process(child);
     child = next;
 }
		`
```
does not produce anything correct for me when using the master git version of run.n

**Comment by dpeek** [comment]
You need triple backticks, like in github flavoured markdown, ie:

```
code
```

**Comment by maxless** [comment]
Ah, that works.

What if I track the opened triple backticks on line X and don't touch any of the following lines until I encounter the next triple backticks at line Y?

**Comment by Simn** [comment]
There might be other things like `<pre>` where whitespaces matter.

**Comment by maxless** [comment]
Something like this. I've added checks for ```<pre>```, too.

**Comment by maxless** [comment]
Added support for 2 or 4 spaces in front and multiple paragraphs.

**Comment by dpeek** [comment]
Ok, I'm going to call this closed by https://github.com/dpeek/dox/commit/35f45b38a02b94d4947c7645e6ba6f39eab3447d

We detect indentation as: the indentation of the line (other than the first) that matches the condition (some spaces/tabs)(optional asterix AND space)(non-space char other than asterix)

Could you please check whatever you were trying to fix and open a new issue if it's still broken?

**Comment by maxless** [comment]
I've checked my tests and documentation, looks fine with your changes. I
don't see any test cases with spaces in TestClass.hx, though, maybe you
should add some test cases there to make sure noone breaks anything later?

2015-05-21 18:10 GMT+04:00 David Peek <notifications@github.com>:

**Comment by dpeek** [comment]
The test is subtle, but it's here:

https://github.com/dpeek/dox/blob/master/test/TestClass.hx#L106

What we really need are some unit tests!

**Comment by Simn** [comment]
Agreed! It's a bit annoying to set up though because it is going to involve some fuzzy string comparing.

**Comment by maxless** [comment]
Well, line 106 has a tab and 2 spaces after that, I was talking about the all-spaces case.

**Pull request closed without merging**
