### PR TITLE
Wrap from/to of Abstract into one title

### PR DESCRIPTION
**Pull request by markknol**
To prettify this http://api.haxe.org/v/dev/haxe/EitherType.html

abstract-from-to

### CODE REVIEW

**Comment by Simn** [comment]
Would it make sense to use nbsp after the to/from so we can be sure not to wrap there?

**Comment by markknol** [comment]
There are already spaces added inbetween the spans and hyperlinks. We could add a nbsp but you'll get a extra space.

**Comment by Simn** [comment]
What I mean is that we should avoid this kind of wrapping:

```
from A from
B
```

and instead have this:

```
from A
from B
```

**Comment by markknol** [comment]
Ah yes, good plan :+1:

**Pull request merged**
