### PR TITLE
Platform dropdown (closes #105)

### LINKED ISSUE #105: Platform select on haxe-api theme is gone
I've just up uploaded the Haxe API docs with the new theme to http://api.haxe.org/v/dev/. Only then I noticed that the platform selection is gone. We'll need that back before we can use it as a default.

@markknol: Could you check this?

### PR DESCRIPTION
**Pull request by markknol**
* added platform dropdown. there was still filter-code worked almost out of box.
* "properties" > "fields"
* inline/dynamic labels

search-filter

### CODE REVIEW

**Comment by Simn** [comment]
Awesome! Could I trouble you for one last thing? I think I forgot to push https://github.com/dpeek/dox/commit/bdca756a4e0f680a3c275383a9b3d02849628f05 which means it's probably not in any other theme. Could you check that it's added?

**Comment by markknol** [comment]
It is not added. I can add this, but what function/variable shows a valid output?

**Comment by Simn** [comment]
There aren't too many in the standard library, but this is one: http://api.haxe.org/haxe/Serializer.html#USE_CACHE

**Comment by markknol** [comment]
I tried to add this, but the `field.expr` seems to be always `null`, what am I doing wrong?

**Comment by Simn** [comment]
Are you generating the XML with latest Haxe?

**Comment by markknol** [comment]
Haha :smile: No.. 

So maybe it's fixed

**Comment by Simn** [comment]
Yeah I think 3.1.3 simply doesn't generate any expression information.

**Pull request merged**
